name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 84532 # Base Sepolia
    start_block: 0
    contracts:
      - name: BetRegistry
        address: "0xA6D58a15918DA51999354F9e47B65111F5bbC124"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User
          - event: BetPlaced
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketResolved
            requiredEntities:
              - name: Market
              - name: User
          - event: BetCashedOut
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketSlashed
            requiredEntities:
              - name: Market
              - name: User
              - name: Dao
      - name: SteakedDegen
        address: "0xDc94924c13978C60676BF7373E896B9862C58A59"
        abi_file_path: ./abi/SteakedDegen.json
        handler: ./src/event-handlers/SteakedDegen.ts
        events:
          - event: DaoFeePaid
            requiredEntities:
              - name: Dao
          