name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 8453 # Base
    start_block: 12942531
    contracts:
      - name: BetRegistry
        address: "0x55a332d75f2BC9937d50084b8D4af7cB9Fa192Fe"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User
          - event: BetPlaced
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketResolved
            requiredEntities:
              - name: Market
              - name: User
          - event: BetCashedOut
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketSlashed
            requiredEntities:
              - name: Market
              - name: User
              - name: Dao
      - name: SteakedDegen
        address: "0xC20e615356D3301bF3eC624585e8c9C88a2096E4"
        abi_file_path: ./abi/SteakedDegen.json
        handler: ./src/event-handlers/SteakedDegen.ts
        events:
          - event: DaoFeePaid
            requiredEntities:
              - name: Dao
          
