name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 31337 # Local
    start_block: 0
    rpc_config:
      url: "http://127.0.0.1:8545"
    contracts:
      - name: BetRegistry
        address: "0x78B4784daD53C0640134e5DC7e4248c9a0c440CB"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User