name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 8453 # Base
    start_block: 12250857
    contracts:
      - name: BetRegistry
        address: "0x8eCa90aB5DD9b876F70D4599651e640B9C172852"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User
          - event: BetPlaced
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketResolved
            requiredEntities:
              - name: Market
              - name: User
          - event: BetCashedOut
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketSlashed
            requiredEntities:
              - name: Market
              - name: User
              - name: Dao
      - name: SteakedDegen
        address: "0x3a857574957ba327287a5a5B3245bFdA7419433c"
        abi_file_path: ./abi/SteakedDegen.json
        handler: ./src/event-handlers/SteakedDegen.ts
        events:
          - event: DaoFeePaid
            requiredEntities:
              - name: Dao
          
