name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 8453 # Base
    start_block: 12250857
    contracts:
      - name: BetRegistry
        address: "0x8aA47373bb61D5CA93098182420A454B7039d1a2"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User
          - event: BetPlaced
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketResolved
            requiredEntities:
              - name: Market
              - name: User
          - event: BetCashedOut
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketSlashed
            requiredEntities:
              - name: Market
              - name: User
              - name: Dao
      - name: SteakedDegen
        address: "0xa30176701DB4Df8023516FFaa9Ee8cBC98E0d359"
        abi_file_path: ./abi/SteakedDegen.json
        handler: ./src/event-handlers/SteakedDegen.ts
        events:
          - event: DaoFeePaid
            requiredEntities:
              - name: Dao
          
