name: SteakedDegenIndexer
description: Indexes Degen Steaks
networks:
  - id: 84532 # Base Sepolia
    start_block: 0
    contracts:
      - name: BetRegistry
        address: "0x68D8E45939926154BD4356105F9bA120169EF606"
        abi_file_path: ./abi/BetRegistry.json
        handler: ./src/event-handlers/BetRegistry.ts
        events:
          - event: MarketCreated
            requiredEntities:
              - name: Market
              - name: Bet
              - name: User
          - event: BetPlaced
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketResolved
            requiredEntities:
              - name: Market
              - name: User
          - event: BetCashedOut
            requiredEntities:
              - name: Bet
              - name: User
              - name: Market
          - event: MarketSlashed
            requiredEntities:
              - name: Market
              - name: User
              - name: Dao
      - name: SteakedDegen
        address: "0xb99e496f3e741b9D1a1E3413ace21c56ea3e5361"
        abi_file_path: ./abi/SteakedDegen.json
        handler: ./src/event-handlers/SteakedDegen.ts
        events:
          - event: DaoFeePaid
            requiredEntities:
              - name: Dao
          